### ISSUE TITLE
Duplicate items

### ISSUE THREAD

**Issue by jgmarcel** [feedbin/support#541] opened 2016-06-19 17:25 UTC
Reproducible steps:

1. Subscribe to the affected feeds (examples follow).
2. Get duplicate items.

Affected feeds:

* https://lifeondoverbeach.wordpress.com/feed/
* https://orthosphere.wordpress.com/feed/
* https://zippycatholic.wordpress.com/feed/

**Comment by benubois** [comment] 2016-06-22 19:14
Hi @jgmarcel,

Sorry for the trouble. This is a problem caused by WordPress. They are inconsistent with article guids so it causes duplicates in Feedbin. They fixed it on their side in the past and I'm hoping they'll fix it again soon.

There's more information about this issue in #431.

Closing this a a duplicate.

Thanks!

**Closed by benubois** 2016-06-22 19:14 UTC
